language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
  - npm run coveralls
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
